//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsServiceShibaeva
{
    using System;
    using System.Collections.Generic;
    
    public partial class ads
    {
        public int ad_id { get; set; }
        public int user_id { get; set; }
        public string ad_title { get; set; }
        public string ad_description { get; set; }
        public int city_id { get; set; }
        public int category_id { get; set; }
        public int type_id { get; set; }
        public int status_id { get; set; }
        public decimal price { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual ad_statuses ad_statuses { get; set; }
        public virtual ad_types ad_types { get; set; }
        public virtual categories categories { get; set; }
        public virtual cities cities { get; set; }
        public virtual users users { get; set; }
    }
}
