//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsServiceShibaeva
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdsServiceShibaevaEntities : DbContext
    {
        public AdsServiceShibaevaEntities()
             : base("name=AdsServiceShibaevaEntities")
        {
        }
        private static AdsServiceShibaevaEntities _context;

        public static AdsServiceShibaevaEntities GetContext()
        {
            if (_context == null) _context = new AdsServiceShibaevaEntities();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ad_statuses> ad_statuses { get; set; }
        public virtual DbSet<ad_types> ad_types { get; set; }
        public virtual DbSet<ads> ads { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
